/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/myModel.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'

export function Avatar(props) {
  const group = useRef()

  const { nodes, materials } = useGLTF('models/myModel.glb')

  const { animations: typingAnimation } = useFBX('animations/Typing.fbx')

  typingAnimation[0].name = 'Typing'

  const {actions} = useAnimations(typingAnimation, group)

  useEffect(() => {
    actions['Typing'].reset().play()
  }, [])


  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh name="Wolf3D_Avatar" geometry={nodes.Wolf3D_Avatar.geometry} material={materials.Wolf3D_Avatar} skeleton={nodes.Wolf3D_Avatar.skeleton} morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('models/myModel.glb')
